### ISSUE TITLE
test-utils.js should be already transpiled

### ISSUE THREAD

**Issue by Ognian** [thebuilder/react-intersection-observer#197]
The distributed test-utils.js starts with an import statement.
Leading to the following jest error:
![image](https://user-images.githubusercontent.com/1231174/54166046-a0b24700-4463-11e9-9334-c9ef69943575.png)
Due to this it must be transpiled...
In your test configuration you are including a __local file__ (not in node_modules) therefore it is not a problem...
Since I use react-create-app it is even impossible to use the ```transformIgnorePatterns``` option

![image](https://user-images.githubusercontent.com/1231174/54166170-51204b00-4464-11e9-99b8-257451feefda.png)

...

Thanks
Ognian

**Comment by thebuilder** [comment]
Good catch, will get that fixed.

**Comment by thebuilder** [comment]
Fixed in v8.22.1 👌

**Comment by Ognian** [comment]
Thanks a lot for the quick fix!
Unfortunately I still have a problem.
This is how I thought it would work:
```
it(`some test`, () => {
      mockAllIsIntersecting(false)
      const tree = renderer
        .create(
          <XXXX
          />
        )
        .toJSON()
      expect(tree).toMatchSnapshot()
    })
```
where XXXX is a component which uses deep inside and often InView
the error I get is:
![image](https://user-images.githubusercontent.com/1231174/54194069-af2c4d00-44bb-11e9-982b-e8cac701b471.png)

Not sure if I'm using it the right way...
Any ideas?

Ognian

**Comment by thebuilder** [comment]
Two issues: 
1) The `mockAllIsIntersecting` only affects existing observers. So you should call it after rendering. It also shouldn't be necessary to to call it with `false`, since the observers are outside the view by default.
2) The error, as it also explains, is because you aren't setting the `ref` on a DOM node. The `IntersectionObserver` needs a HTMLElement it can observe, and it gets that from the `ref.

I'd also recommend using [react-testing-library](https://testing-library.com/docs/react-testing-library/intro) instead of creating a Snapshot test.

**Comment by Ognian** [comment]
But I'm using it this way:
```
 <InView as="div" onChange={this.handleInView}>
```
so everything should happen in InView ....
and in the app everything works as expected; only the tests fail....

**Comment by Ognian** [comment]
OK for everyone else stumbling on this:
If you need snapshot testing, you can "simply" mock InView:
```
jest.mock('react-intersection-observer', ()=>({
  InView: 'mockInView'
}))
```
What I also found out is, that sometimes snapshots (the .snap file) can get "corrupt", resulting in an endless running test -> remove it ...
